### ISSUE TITLE
urlencode causes label is not found

### ISSUE THREAD

**Issue by jbanety** [joomla-framework/github-api#33]
### Steps to reproduce the issue

```php
$label = "my label"; // my label exists in the repo
$github->issues->labels->get($owner, $repo, $label);
```

### Expected result

Status: 200 OK

### Actual result

Status: 404 Not found

### Additional comments

urlencode encodes space as `+` and GitHub api does not support plus sign as space.

**Comment by mbabker** [comment]
https://github.com/joomla-framework/github-api/commit/2392682e84b131d569e63632086dee7340c6a125 didn't fix it?

**Comment by jbanety** [comment]
Sorry, I didn't mention that I'm using the 2.0-dev branch.
And Yes, with the 1.5.2 version It did fix the issue.
